name: Notify Discord on Pull Request Events

on:
  pull_request:
    branches:
      - main
    types: [opened, review_requested, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Assign team to review pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const team = 'diucse-alumni-developers';
            const teamMembers = await github.teams.listMembersInOrg({ org: 'Softanglez-Coder', team_slug: team });
            const teamMemberUsernames = teamMembers.data.map(member => member.login);
            const teamMemberUsernamesString = teamMemberUsernames.join(' ');
            github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: teamMemberUsernamesString.split(' ')
            });

      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_CODE_REVIEW }}
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            MESSAGE="A new pull request has been created: ${{ github.event.pull_request.html_url }}"
          elif [ "${{ github.event.action }}" == "review_requested" ]; then
            MESSAGE="A pull request has been marked for review: ${{ github.event.pull_request.html_url }}"
          elif [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            MESSAGE="A pull request has been merged: ${{ github.event.pull_request.html_url }}"
          else
            MESSAGE=""
          fi

          if [ ! -z "$MESSAGE" ]; then
            curl -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
          fi
