name: Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build:all

      - name: Check for Core changes and release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep -q "projects/diucsealumni/core" || [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "Core package has changes, running semantic-release..."
            cd projects/diucsealumni/core
            npx semantic-release
          else
            echo "No changes in core package, skipping release."
          fi

      - name: Check for Models changes and release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep -q "projects/diucsealumni/models" || [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "Models package has changes, running semantic-release..."
            cd projects/diucsealumni/models
            npx semantic-release
          else
            echo "No changes in models package, skipping release."
          fi

      - name: Check for Services changes and release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep -q "projects/diucsealumni/services" || [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "Services package has changes, running semantic-release..."
            cd projects/diucsealumni/services
            npx semantic-release
          else
            echo "No changes in services package, skipping release."
          fi

      - name: Check for Utils changes and release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep -q "projects/diucsealumni/utils" || [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "Utils package has changes, running semantic-release..."
            cd projects/diucsealumni/utils
            npx semantic-release
          else
            echo "No changes in utils package, skipping release."
          fi

      - name: Send notification to Discord
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_GENERAL }}
        run: |
          MESSAGE="New package releases have been published: ${{ github.event.repository.html_url }}/releases/latest"
          curl -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
